project_name: plubo-cli
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
- maintainer: Joan Rodas Cusidó <joan@sirvelia.com>
  description: Plubo CLI
  homepage: https://www.plubo.dev/
  license: GNU GPLv3
  formats:
  - deb
  - rpm
  - archlinux
